Repository netguru/heroes-api, pull requests merged in 2019-10, with the labels that each got.

#25 fix: add cors to rest api
  package.json
  src/server-rest.ts
Labels: ready for review

#26 chore(deps): bump dependencies to fix security issues
  package-lock.json
Labels: ready for review

#27 docs: guidance with links and structured setup
  README.md
Labels: ready for review

#28 feat: query heroes with type [rest-api]
  src/rest/controllers/Heroes.ts
  src/utils/fragments.ts
Labels: ready to merge, rest api

#29 Develop -> Master
  src/rest/controllers/Heroes.ts
  src/utils/fragments.ts
Labels: ready for review

#30 fix: eliminate problem with updating description field in hero model [PUT request]
  src/rest/controllers/Heroes.ts
Labels: ready to merge, rest api

#31 Develop -> QA
  src/rest/controllers/Heroes.ts
Labels: ready to merge
