Repository netguru/heroes-api, pull requests merged in 2019-08, with the labels that each got.

#20 chore: add license and update shields
  LICENSE.txt
  README.md
Labels: ready to merge

#21 docks: modified readme
  README.md
Labels: ready for code review

#23 fix: use query params for heroes endpoint
  src/rest/controllers/Heroes.ts
Labels: ready for review
